"""Initial

Revision ID: e341df33cace
Revises:
Create Date: 2026-05-09 20:13:23.872665

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e341df33cace"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "processed_events",
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("saga_id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.Text(), nullable=False),
        sa.Column("processed_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("event_id"),
    )
    op.create_index(
        op.f("ix_processed_events_saga_id"),
        "processed_events",
        ["saga_id"],
        unique=False,
    )
    op.create_table(
        "saga_state",
        sa.Column("saga_id", sa.UUID(), nullable=False),
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column(
            "state",
            sa.Enum(
                "CREATED",
                "INVENTORY_RESERVING",
                "INVENTORY_RESERVED",
                "PAYMENT_CHARGING",
                "COMPLETED",
                "COMPENSATING_INVENTORY",
                "CANCELLED",
                "FAILED",
                name="sagastateenum",
            ),
            nullable=False,
        ),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("retry_after", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("saga_id"),
    )
    op.create_index(
        op.f("ix_saga_state_order_id"), "saga_state", ["order_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_saga_state_order_id"), table_name="saga_state")
    op.drop_table("saga_state")
    op.drop_index(op.f("ix_processed_events_saga_id"), table_name="processed_events")
    op.drop_table("processed_events")
    # ### end Alembic commands ###
